name: lox
version: 0.0.1
description: >-
  The Lox interpreter, implemented in Dart, thanks to Bob Nystrom's
  Crafting Interpreters book. 
author: Tim Sneath <tim@sneath.org>
environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  dart_console: 
    path: ../dart_console